[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "g8#LzYw!b7R@uT9nE1qA$v2Fh%CmK^x6pSdJ*tWQMI3eUZ5oX"

[auth.google]
client_id = "427446001284-sdf2n6pv2mdpknepa9qcc1d7a25s15o1.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"